export default {
  host: 'sushi-woki.ru',
  filterTrack: true,
  sessionMaxInterval: 20 * 60 * 1000,
  sessionMinLength: 4,
  sessionMaxLength: 25,
  targetUrlFragment: 'route=checkout/success',
  targetClassId: 1,
  anotherClassId: 2,
  aliases: {
    main: ['sushi-woki\.ru\/?$'],
    cart: ['/simplecheckout'],
    profile: [
      '/login',
      '/forgot-password',
      '/my-account',
      '/simple-create-account',
      '/simpleedit-account',
      '/order-history',
      '/change-password',
      '/newsletter',
      '/logout',
      '?route=account',
      '/support',
    ],
    productGroup1: ['/prostye-rolly', '/sushi'],
    productGroup2: ['/pizza'],
    productGroup3: ['/slozhnye-rolly', '/sladkie-rolly'],
    productGroup4: ['/sety'],
    productGroup6: ['/dobavki', '/napitki'],
    productGroup7: ['/wok'],
    info: [
      'oplata_dostavka',
      '?route=latest',
      '/akcii',
      '/about_us',
      '/otzyvy',
      '/address-book',
      '/contact',
      '/contacts',
    ],
  },
}
