name: click-map-api CD

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-18.04

    steps:
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ DOCKER_USER }}
          password: ${{ DOCKER_PASSWORD }}
          repository: mgcat/click-map-api
          tag: ${{ outputs.build.tags }}
