name: click-map-api CD

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-18.04

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.0.0
      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "14.5.0"
      - name: install pnpm
        run: npm install -g pnpm
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t click-map-api .
      - name: Tags
        run: |
          docker tag click-map-api ${{ secrets.DOCKER_USER }}/click-map-api:${{ github.sha }}
          docker tag click-map-api ${{ secrets.DOCKER_USER }}/click-map-api:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/click-map-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/click-map-api:latest
