name: click-map-api CD

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mgcat/click-map-api
          tags: latest
          build_args: DB_HOST=${{ secrets.DB_HOST }},DB_USER=${{ secrets.DB_USER }},DB_NAME=${{ secrets.DB_NAME }},DB_PASS=${{ secrets.DB_PASS }}
