name: click-map-api CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: znck/pnpm@v0.1.0-alpha.1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t click-map-api .
      - name: Tags
        run: |
          docker tag click-map-api ${{ secrets.DOCKER_USER }}/click-map-api:${{ github.sha }}
          docker tag click-map-api ${{ secrets.DOCKER_USER }}/click-map-api:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/click-map-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/click-map-api:latest
